services:
  web:
    container_name: threejsdemo-web
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - savinien
    environment:
      - NODE_ENV=development

networks:
  savinien:
    external: true
